Ext.define('SpicersOrder.view.MIProductList', {
	extend : 'Ext.List',
	xtype : 'miProductList',
	config : {
		flex : 3,
		refreshHeightOnUpdate : true,
		emptyText : 'Loading product information...',
		itemTpl : [
				'<tpl if="lastOrdDays &gt; 30">',
				'<table style="table-layout: fixed; width: 100%; border-left-width: 3px; border-left-style: solid; border-left-color: red;">',				
				'</tpl>',								
				'<tpl if="lastOrdDays &gt; 7 && lastOrdDays &lt;= 30">',
				'<table style="table-layout: fixed; width: 100%; border-left-width: 3px; border-left-style: solid; border-left-color: yellow;">',				
				'</tpl>',								
				'<tpl if="lastOrdDays &lt;= 7">',
				'<table style="table-layout: fixed; width: 100%; border-left-width: 3px; border-left-style: solid; border-left-color: green;">',				
				'</tpl>',								
				'<tr>',						
				'<td style="width:83%" class="mi_general_text"><b>{prodDesc}</b></td>',
				'<tpl if="agedStock == \'X\'">',
					'<td style="width:12%" class="aged_stock"></td>',
				'</tpl>',								
				'<tpl if="atpFlag == \'3\'">',
					'<td style="width:5%" class="red_icon" ></td>',
				'</tpl>',								
				'<tpl if="atpFlag== \'2\'">',
					'<td style="width:5%" class="yellow_icon" ></td>',
				'</tpl>',								
				'<tpl if="atpFlag== \'1\'">',
					'<td style="width:5%" class="green_icon" ></td>',
				'</tpl>',								
				'</tr>',
				'</table>',
				'<table style="width:100%">',
				'<tr>',
				'<td style="width:27%">',
				'<div class="mi_general_text">#{prodNo}</div>',
				'</td>',
				'<td style="width:35%">',
				'<div class="mi_general_text">Lst Quo: {lastQuoDays}</div>',
				'</td>',
				'<td style="width:38%">',
					'<div class="mi_general_text">Lst Ord: <b>{lastOrdDays}</b></div>',
				'</td>',
				'</tr>',
				'<tr>',
				'<td style="width:27%">',
				'<div class="mi_general_text">MTD: <b>{[number(values.mtdSales, true)]}</b></div>',
				'</td>',
				'<td style="width:35%">',
				'<div class="mi_general_text">Lst Mth: <b>{[number(values.lastMthSales, true)]}</b></div>',
				'</td>',
				'<td style="width:38%">',
				'<div class="mi_general_text">Avg 6 Mth: <b>{[number(values.avg6MthSales, true)]}</b></div>',
				'</td>',
				'</tr>',
				'<tpl if="requestStatus != \'\'">',
				'<tr>',
				'<td style="width:27%">',
				'<div class="mi_general_text">Future: <b>{[number(values.futureMthSales)]}</b></div>',
				'</td>',
				'<td style="width:35%">',
				'<div class="mi_general_text">From: <b>{[convertToDMYDate(values.fromDate)]}</b></div>',
				'</td>',
				'<td style="width:38%">',
				'<div class="mi_general_text">To: <b>{[convertToDMYDate(values.toDate)]}</b></div>',
				'</td>',
				'</tr>',
				'</tpl>',												
				'</table>',
				
				],
		store : {
			type : 'miProduct'
		}
	}
});