Ext.define('SpicersOrder.view.ProductMIHistList', {
    extend : 'Ext.List',
    xtype : 'productMIHistList',
    config : {
        title : 'MI History',
        scrollable : true,
		grouped : true,
		emptyText : 'No market intelligence information',
        disableSelection: true,
        itemTpl : [
		'<table style="width:100%">',
			'<tr>',
				'<td style="width:25%"><div class="mi_hist_general_text">Future: <b>{[number(values.futureMthSales)]}</b></div></td>',
				'<td style="width:75%"><div class="mi_hist_general_text">Reason: {reason}</div></td>',
			'</tr>',
		'</table>',
		'<table style="width:100%">',
			'<tr>',
				'<td style="width:100%"><div class="mi_hist_general_text">Detail: {detail}</div></td>',
			'</tr>',
		'</table>',
		'<table style="width:100%">',
			'<tr>',
				'<td style="width:50%"><div class="mi_hist_general_text">From: {[convertToDMYDate(values.fromDate)]}</div></td>',
				'<td style="width:50%"><div class="mi_hist_general_text">To: {[convertToDMYDate(values.toDate)]}</div></td>',
			'</tr>',
			'<tr>',
				'<td style="width:50%"><div class="mi_hist_general_text">CreatedBy: {createdBy}</div></td>',
				'<td style="width:50%"><div class="mi_hist_general_text">CreatedDate: {[convertToDMYDate(values.creationDate)]}</div></td>',
			'</tr>',
		'</table>',
		],
    }
});
